# CMakeLists.txt in main

FILE(GLOB SRCFILES *.cxx)
FILE(GLOB HFILES TT*.h)

ROOT_STANDARD_LIBRARY_PACKAGE(
        THERMUS
    HEADERS
        ${HFILES}
    SOURCES
        ${SRCFILES}
    DEPENDENCIES
        ${ROOT_LIBRARIES})

set_target_properties(THERMUS PROPERTIES PUBLIC_HEADER "${HFILES}")

install(TARGETS THERMUS
    PUBLIC_HEADER DESTINATION ${CMAKE_INSTALL_INCLUDEDIR})

install(FILES ${CMAKE_BINARY_DIR}/main/libTHERMUS_rdict.pcm 
    ${CMAKE_BINARY_DIR}/main/libTHERMUS.rootmap
    DESTINATION ${CMAKE_INSTALL_LIBDIR})
