name: clang- format
on:
  push:

jobs:
  clang-format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: run clang-format script
      run: clang-format --dry-run -Werror --files=.clang_files
